server:
  port: 31001
spring:
  data:
    mongodb:
      host: 122.51.150.222
      #      host: localhost
      port: 27017
      database: admin
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 122.51.150.222
    port: 5672
    username: guest
    password: guest
    virtual-host: /